// things they need to do: 
// 1.Maek the sprite move
// 2. make the gost move
// 3. make the ghost stay on screen
// 4. fix code for key
// 5. change the effect when the game is over to bubbles. 
sprites.onOverlap(SpriteKind.Projectile, SpriteKind.Food, function (sprite, otherSprite) {
    game.setGameOverEffect(true, effects.splatter)
    game.gameOver(true)
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Projectile, function (sprite, otherSprite) {
    mySprite3.setPosition(6, 106)
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Enemy, function (sprite, otherSprite) {
    mySprite3.setPosition(6, 106)
})
// This game is the devi jones crew game. make it moderately hard. Code ideas include debug.
let mySprite3: Sprite = null
let ZORAVAR: Sprite = null
scene.setBackgroundColor(2)
ZORAVAR = sprites.createProjectileFromSprite(img`
    ....................................................................................................
    ....................................................................................................
    ....................................................................................................
    ....................................................................................................
    ....................................................................................................
    ....................................................................................................
    ....................................................................................................
    ....................................................................................................
    ....................................................................................................
    ....................................................................................................
    ....................................................................................................
    ....................................................................................................
    ....................................................................................................
    ....................................................................................................
    ....................................................................................................
    ....................................................................................................
    ....................................................................................................
    ....................................................................................................
    ................................................................f...................................
    .................................................ffff..........fff..................................
    ................................................ffffff.........fff..................................
    ................................................ffffff........fffff.................................
    ...............................................fffffff........fffff.................................
    ...............................................ffffffff......ffffff.................................
    ..............................................ffffffffff....fffffff.................................
    ..............................................fffffffffff..ffffffff.................................
    .............................................fffffffffffffffffffffff................................
    ............................................ffffffffffffffffffffffff................................
    ..........................................ffffffffffffffffffffffffffff..............................
    .......................................fffffffffffffffffffffffffffffffff............................
    .....................................ffffffffffffffffffffffffffffffffffff...........................
    ....................................ffffffffffffffffffffffffffffffffffffff..........................
    ...................................ffffffffffffffffffffffffffffffffffffffff.........................
    ...................................fffffffffffffffffffffffffffffffffffffffff........................
    ..................................fffffffffffffffffffffffffffffffffffffffffff.......................
    ..................................fffffffffffffffffffffffffffffffffffffffffff.......................
    ..................................ffffffffffffffffffffffffffffffffffffffffffff......................
    .................................fffffffffffffffffffffffffffffffffffffffffffff......................
    .................................ffffffffffffffffffffffffffffffffffffffffffffff.....................
    .................................ffffffffffffffffffffffffddddddffffffffffffffff.....................
    .................................fffffffffffffffddddddddddddddddfffffffffffffff.....................
    .................................fffffffffffffdddddddddddddddddddffffffffffffff.....................
    .................................fffffffffffddddddddddddddddddddddfffffffffffff.....................
    .................................fffffffffffdddddddddddddddddddddddffffffffffff.....................
    ..................................ffffffffdddddfffddddddddddddfdddddfffffffffff.....................
    ..................................ffffffffdddddddfffdddddfffffdddddddffffffffff.....................
    ........................ff........ffffffffdddddddfffffdddffffddddddddddffffffff.....................
    ........................fffff.....ffffff.fdddddddfdfdfddddfdfdddddddddddffffff......................
    ........................fdddff....fffff.ffdddddddfffddddddfffdddddfdddffffff........................
    ........................ffdddff...ffff..fddddddddddddddddddddddddddfddffff..........................
    .........................ffdddf...ff....fdddddddddddddddddddddddddddfdff....fff.....................
    ..........................fdddf...f.....fddddfddddddddddddddddddddddfdf....ffdff....................
    ...........................fddf.........fdddfddddddddfdfddddddddfddddfdf..ffddfff...................
    ............................fdf.........fddffddddddddddddddddfddfdfdddff..fddffdf...................
    ............................fdff........fddfdddddddddddddddddffddfdfdddff.fddffdf...................
    ............................ff.f.......fdddfdddddddfddddddddddfddfdffddfffdddffdf...................
    .............................ffdff....ffdddfdddffddfddfddfdfddfddfddffddffddfffff...................
    ..............................fdfdfffffddddfddfffddfddfddfdfdddffdfddffdddfdf...f...................
    ..............................ffdddddddddddfdffffddfdfdddfdfdddffdffddfffdfdf.......................
    .............................ffffdddddddddfddfdfddffdfdfdfddfddffddffddffffff.......................
    .......................fffffffddffdddfffddfdfddfddffdfdfdfddfddfffddffdddff.........................
    .......................fdddddddddffffffdffdfddfddffffddfdffdfddfdfdddffdddffff......................
    .......................fdddfffffff..ffddfdfdddfddfdffddfddffdfdffffdddfddddddff.....................
    .............ffffffffffffdff........fddddffddffdffdfdddffdddffddddfddddfdddddddffff.................
    ..............fffddddddffff.........fdddffdddfddfdffdddf.fddfdfdddffddddfddddddddddfff..............
    ................ffffddddffff.......fddddfdfddfddfdffdddf.fddfdfddddffddddffddddddddddfff............
    ...................fffddddddf....fffdddfdfdddfddfdffdddf.fddfddfddddfddddddffddddddddddff...........
    ......................ffdddddffffdddddfdfdddfdddfdffdddf.fddfdfdfddddfdddddddffffdddddddff..........
    ...............ffffffffffffffddddddfffdfddddfdddffffdddf.fddfdfdffdddffddddddddddffffffffff.........
    ............fffdddddddddddddffffffffddffdddfdddfffffdddf.fddfddfdfdffddffdddddddddddddddfff.........
    ..........fffddddddddddddddddddddfffdfddddfdddfddfffdddf.fddfddfddffdfdddfffddddddddddddddff........
    .........ffdddddddddddddddddddffffddfddddffdddfdffffdddf.fddfddfddfffdfddddffffffddddddddddf........
    ........ffdddddddfffffffffffff.ffdddddddffddddfdfddffddf.fddddddfddfffdfddddffdddfffffffddddf.......
    ........fddddddfff..........fffddddddfffdddddfddfddffddf..fdddddfddf.ffdfddddfdddddddddfffddf.......
    .......ffddddfff..........fffdddddffffddddddffdffddffddf..ffdddddfddf..fdfdddffddddddddfffffff......
    .......fdddfff..........ffdddddddfffddddddffdddfddddfddff..ffdddddfddf..fdfddf.fffddddddff.fff......
    ......fdddff...........fdddddfffffffdddddfddddfffddffdddf...ffddddfddf..ffdddf...ffddddddf..ff......
    ......fddff............fddfff.....fdddddffddddffdddfffddf....ffdddfddf...fdddf.....ffdddddf.ff......
    ......fdff...........ff.ff........fddddfdddddf.fdddfffddf.....fddddddf...fdddf.......fddddf..ff.....
    ......fff............f.ff.........fddddfddddff.fdddfffddf.....ffddfdddf..ffddf........fddddf..f.....
    ......ff.............ff...........fddffdddfff..fddff.fddf......fddfdddf...fddf........fdddf...f.....
    .....................f............fddfddfff....fddf..ffdf......fddffdddf..fdff.........fddf...f.....
    ..................................fddddf.......fdff...fdf......ffdffdddf..fdf..........fddf...ff....
    ..................................fddff........fdf....fff.......fdfffddf..fdf..........fddf...ff....
    ..................................fdff.........ff.....ff........fdf.fddf..fff...........ff..........
    ..................................ff...........ff.....f..........ff.fddf...ff...........ff..........
    ..................................ff...........ff.....f..........ff.fddf...ff...........ff..........
    ...............................................f......f..........ff.fddf...f............f...........
    .................................................................ff.fddf................f...........
    .....................................................................fff............................
    .....................................................................ff.............................
    .....................................................................ff.............................
    ....................................................................................................
    ....................................................................................................
    ....................................................................................................
    ....................................................................................................
    ....................................................................................................
    ....................................................................................................
    ....................................................................................................
    ....................................................................................................
    `, ZORAVAR, 40, 40)
ZORAVAR.setPosition(83, 60)
ZORAVAR.setScale(0.5, ScaleAnchor.Middle)
// they can select their own avatar. this avatar goes and finds the chest. They have to code for the sprite to move.
mySprite3 = sprites.create(img`
    . . . . . . . 5 . 5 . . . . . . 
    . . . . . . f 5 5 5 f . . . . . 
    . . . . . f 6 5 5 2 6 f . . . . 
    . . . . f 6 6 1 6 6 6 6 f . . . 
    . . . . f 6 1 6 6 6 6 6 f . . . 
    . . . . f 1 6 6 6 d f d f . . . 
    . . . f f 6 6 6 6 d f d f . . . 
    . . f 6 f 6 6 6 d d 3 d f . . . 
    . . . f f 6 f f d d d f . . . . 
    . . f 6 6 6 f 3 5 f f . . . . . 
    . . . f f f f f 3 3 5 f . . . . 
    . . . . . . f d f 3 3 f . . . . 
    . . . . . . f d f 3 f . . . . . 
    . . . . . f d f 3 5 3 f . . . . 
    . . . . . . f f 3 3 f f . . . . 
    . . . . . . . f f f . . . . . . 
    `, SpriteKind.Player)
let mySprite4 = sprites.create(img`
    . . . . 5 5 5 5 5 . . . . . . . 
    . . . . 5 5 5 5 5 . . . . . . . 
    . . . . 5 5 . 5 5 . . . . . . . 
    . . . . 5 5 5 5 5 . . . . . . . 
    . . . . 5 5 5 5 5 . . . . . . . 
    . . . . . . 5 5 . . . . . . . . 
    . . . . . . 5 5 . . . . . . . . 
    . . . . . . 5 5 . . . . . . . . 
    . . . . . . 5 5 . . . . . . . . 
    . . . . . . 5 5 . . . . . . . . 
    . . . . . . 5 5 . . . . . . . . 
    . . . . . . 5 5 . . . . . . . . 
    . . . . 5 5 5 5 . . . . . . . . 
    . . . . . . 5 5 . . . . . . . . 
    . . . . 5 5 5 5 . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    `, SpriteKind.Food)
mySprite4.setPosition(148, 14)
mySprite3.setPosition(6, 106)
let mySprite2 = sprites.create(img`
    ........................
    ........................
    ........................
    ........................
    ..........ffff..........
    ........ff1111ff........
    .......fb111111bf.......
    .......f11111111f.......
    ......fd11111111df......
    ......fd11111111df......
    ......fddd1111dddf......
    ......fbdbfddfbdbf......
    ......fcdcf11fcdcf......
    .......fb111111bf.......
    ......fffcdb1bdffff.....
    ....fc111cbfbfc111cf....
    ....f1b1b1ffff1b1b1f....
    ....fbfbffffffbfbfbf....
    .........ffffff.........
    ...........fff..........
    ........................
    ........................
    ........................
    ........................
    `, SpriteKind.Enemy)
mySprite2.setPosition(30, 37)
mySprite2 = sprites.create(img`
    ........................
    ........................
    ........................
    ........................
    ..........ffff..........
    ........ff1111ff........
    .......fb111111bf.......
    .......f11111111f.......
    ......fd11111111df......
    ......fd11111111df......
    ......fddd1111dddf......
    ......fbdbfddfbdbf......
    ......fcdcf11fcdcf......
    .......fb111111bf.......
    ......fffcdb1bdffff.....
    ....fc111cbfbfc111cf....
    ....f1b1b1ffff1b1b1f....
    ....fbfbffffffbfbfbf....
    .........ffffff.........
    ...........fff..........
    ........................
    ........................
    ........................
    ........................
    `, SpriteKind.Enemy)
mySprite2.setPosition(134, 25)
mySprite2 = sprites.create(img`
    ........................
    ........................
    ........................
    ........................
    ..........ffff..........
    ........ff1111ff........
    .......fb111111bf.......
    .......f11111111f.......
    ......fd11111111df......
    ......fd11111111df......
    ......fddd1111dddf......
    ......fbdbfddfbdbf......
    ......fcdcf11fcdcf......
    .......fb111111bf.......
    ......fffcdb1bdffff.....
    ....fc111cbfbfc111cf....
    ....f1b1b1ffff1b1b1f....
    ....fbfbffffffbfbfbf....
    .........ffffff.........
    ...........fff..........
    ........................
    ........................
    ........................
    ........................
    `, SpriteKind.Enemy)
mySprite2.setPosition(37, 88)
mySprite2 = sprites.create(img`
    ........................
    ........................
    ........................
    ........................
    ..........ffff..........
    ........ff1111ff........
    .......fb111111bf.......
    .......f11111111f.......
    ......fd11111111df......
    ......fd11111111df......
    ......fddd1111dddf......
    ......fbdbfddfbdbf......
    ......fcdcf11fcdcf......
    .......fb111111bf.......
    ......fffcdb1bdffff.....
    ....fc111cbfbfc111cf....
    ....f1b1b1ffff1b1b1f....
    ....fbfbffffffbfbfbf....
    .........ffffff.........
    ...........fff..........
    ........................
    ........................
    ........................
    ........................
    `, SpriteKind.Enemy)
mySprite2.setPosition(119, 81)
mySprite2 = sprites.create(img`
    ........................
    ........................
    ........................
    ........................
    ..........ffff..........
    ........ff1111ff........
    .......fb111111bf.......
    .......f11111111f.......
    ......fd11111111df......
    ......fd11111111df......
    ......fddd1111dddf......
    ......fbdbfddfbdbf......
    ......fcdcf11fcdcf......
    .......fb111111bf.......
    ......fffcdb1bdffff.....
    ....fc111cbfbfc111cf....
    ....f1b1b1ffff1b1b1f....
    ....fbfbffffffbfbfbf....
    .........ffffff.........
    ...........fff..........
    ........................
    ........................
    ........................
    ........................
    `, SpriteKind.Enemy)
mySprite2.setPosition(78, 98)
ZORAVAR.setBounceOnWall(true)
ZORAVAR.startEffect(effects.bubbles)
// code this to move up/down
mySprite2 = sprites.create(img`
    ........................
    ........................
    ........................
    ........................
    ..........ffff..........
    ........ff1111ff........
    .......fb111111bf.......
    .......f11111111f.......
    ......fd11111111df......
    ......fd11111111df......
    ......fddd1111dddf......
    ......fbdbfddfbdbf......
    ......fcdcf11fcdcf......
    .......fb111111bf.......
    ......fffcdb1bdffff.....
    ....fc111cbfbfc111cf....
    ....f1b1b1ffff1b1b1f....
    ....fbfbffffffbfbfbf....
    .........ffffff.........
    ...........fff..........
    ........................
    ........................
    ........................
    ........................
    `, SpriteKind.Enemy)
effects.blizzard.startScreenEffect()
scene.cameraFollowSprite(mySprite3)
